import {
  Plane,
  Building,
  Map,
  Compass,
  Calendar,
  Sun,
  Cloud,
  Wallet,
  Briefcase,
  Star,
  User,
  Settings,
  Shield,
  Search,
  Menu,
  X,
  Check,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Bell,
  Share,
  Plus,
  Trash,
  Edit,
  ArrowRight,
  Info,
  AlertTriangle,
  AlertCircle,
  Loader2,
  Moon,
  LogOut,
  MapPin,
  Clock,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Lock,
  Mail,
  Sliders,
  Sparkles,
  Footprints,
  Car,
  Train,
  Bike,
} from "lucide-react";

/**
 * Centralized Icon Export System.
 * Enables easy switching of icon libraries or custom SVGs in the future.
 */
export const Icons = {
  // Travel Specific
  flight: Plane,
  hotel: Building,
  map: Map,
  explore: Compass,
  calendar: Calendar,
  weatherSun: Sun,
  weatherCloud: Cloud,
  budget: Wallet,
  packing: Briefcase,
  destination: MapPin,
  time: Clock,
  star: Star,
  walk: Footprints,
  car: Car,
  train: Train,
  bike: Bike,
  
  // UI General
  search: Search,
  menu: Menu,
  close: X,
  check: Check,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  notification: Bell,
  share: Share,
  plus: Plus,
  trash: Trash,
  edit: Edit,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  externalLink: ExternalLink,
  
  // Status & Feedback
  info: Info,
  warning: AlertTriangle,
  error: AlertCircle,
  spinner: Loader2,
  sparkles: Sparkles,
  
  // Account & Auth
  user: User,
  settings: Settings,
  auth: Shield,
  lock: Lock,
  mail: Mail,
  logout: LogOut,
  themeLight: Sun,
  themeDark: Moon,
  filter: Sliders,
};

export type IconType = keyof typeof Icons;
