import { DestinationKnowledgeProvider } from "./knowledge-provider";
import { DestinationKnowledge, Attraction } from "../types";

// Helper to generate mock reviews
const createMockReviews = (title: string) => [
  { author: "Sarah Jenkins", rating: 5, text: "Absolutely stunning! The sunset views here are out of this world.", date: "2 days ago" },
  { author: "Markus Aurelius", rating: 4, text: "Long queues after 11 AM. Pro tip: Buy skip-the-line tickets online.", date: "1 week ago" }
];

const createMockImages = (query: string) => [
  "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1549144511-f099e773c147?auto=format&fit=crop&w=800&q=80"
];

const createMockBusyHours = () => ({
  "9 AM": "Low",
  "12 PM": "High",
  "3 PM": "Medium",
  "6 PM": "Medium"
});

const MOCK_DESTINATIONS: Record<string, DestinationKnowledge> = {
  rome: {
    destination: "Rome",
    country: "Italy",
    region: "Lazio",
    coordinates: { lat: 41.9028, lng: 12.4964 },
    language: "Italian",
    currency: "EUR",
    timezone: "GMT+1",
    bestSeason: "April to June",
    safetyScore: 89,
    crowdLevels: "high",
    weatherSummary: "Mild spring/autumn, hot summers, cool winters.",
    visaNotes: "Schengen Visa rules apply.",
    emergencyContacts: { police: "112", medical: "118", fire: "115" },
    transportation: ["Metro A/B", "Rome Trams", "Buses"],
    averageCosts: { accommodation: "$130/night", food: "$35/day", transit: "$6/day", sightseeing: "$30/day" },
    mustVisitAttractions: [
      {
        title: "Colosseum",
        description: "The giant 1st-century gladiatorial amphitheater in the center of Rome.",
        cost: "$18",
        averageVisitDuration: "2h",
        bestTimeOfDay: "morning",
        coordinates: { lat: 41.8902, lng: 12.4922 },
        openingHours: "08:30 AM - 07:00 PM",
        categories: ["landmark", "culture"],
        popularity: 99,
        accessibility: ["wheelchair_accessible"],
        weatherDependency: "high",
        photographyScore: 10,
        googleRating: 4.8,
        googleReviewsCount: 342500,
        reviews: createMockReviews("Colosseum"),
        images: createMockImages("Colosseum"),
        busyHours: createMockBusyHours(),
        bookingUrl: "https://www.coopculture.it"
      },
      {
        title: "Trevi Fountain",
        description: "The baroque masterpiece fountain designed by Nicola Salvi.",
        cost: "Free",
        averageVisitDuration: "45m",
        bestTimeOfDay: "night",
        coordinates: { lat: 41.9009, lng: 12.4833 },
        openingHours: "24/7",
        categories: ["landmark", "photography"],
        popularity: 98,
        accessibility: [],
        weatherDependency: "low",
        photographyScore: 10,
        googleRating: 4.7,
        googleReviewsCount: 295000,
        reviews: createMockReviews("Trevi Fountain"),
        images: createMockImages("Trevi Fountain"),
        busyHours: createMockBusyHours()
      }
    ],
    hiddenGems: [
      {
        title: "Villa Celimontana",
        description: "A peaceful 16th-century park on the Caelian Hill.",
        cost: "Free",
        averageVisitDuration: "1.5h",
        bestTimeOfDay: "afternoon",
        coordinates: { lat: 41.8845, lng: 12.4962 },
        openingHours: "07:00 AM - Sunset",
        categories: ["nature", "family"],
        popularity: 62,
        accessibility: [],
        weatherDependency: "high",
        photographyScore: 8,
        isHiddenGem: true,
        googleRating: 4.5,
        googleReviewsCount: 1200,
        reviews: createMockReviews("Villa Celimontana"),
        images: createMockImages("Villa Celimontana"),
        busyHours: createMockBusyHours()
      }
    ],
    dining: {
      streetFood: [{ name: "Supplizio", cuisine: "Supplì & Roman Snacks", averageCost: "$6", description: "Authentic Roman fried rice balls." }],
      fineDining: [{ name: "Armando al Pantheon", cuisine: "Roman Pasta", averageCost: "$35", description: "Classic Roman carbonara." }],
      cafes: [{ name: "Sant'Eustachio", cuisine: "Specialty Espresso", averageCost: "$3", description: "Famous espresso bar." }]
    },
    nightlife: ["Trastevere bar crawling"],
    adventureActivities: [],
    museums: ["Vatican Museums"],
    parks: ["Villa Borghese"],
    temples: ["St. Peter's"],
    historicalSites: ["Colosseum"],
    shoppingAreas: ["Via del Corso"],
    markets: ["Campo de Fiori"],
    soloExperiences: [],
    coupleExperiences: [],
    familyAttractions: [],
    luxuryExperiences: [],
    budgetExperiences: [],
    localFestivals: ["Natale di Roma"],
    travelTips: { touristScams: ["Gladiators charging for photos"], packingTips: ["Modest clothing for churches"], generalTips: ["Book tickets online"] },
    popularityScore: 98,
    userRating: 4.8,
    nearbyRecommendations: {}
  },
  newyork: {
    destination: "New York",
    country: "United States",
    region: "New York State",
    coordinates: { lat: 40.7128, lng: -74.0060 },
    language: "English",
    currency: "USD",
    timezone: "EST",
    bestSeason: "September to November",
    safetyScore: 88,
    crowdLevels: "high",
    weatherSummary: "Cold winters, warm humid summers, pleasant spring and autumn.",
    visaNotes: "ESTA required for most international visitors.",
    emergencyContacts: { police: "911", medical: "911", fire: "911" },
    transportation: ["NYC Subway", "MTA Buses", "Yellow Cabs"],
    averageCosts: { accommodation: "$220/night", food: "$50/day", transit: "$12/day", sightseeing: "$40/day" },
    mustVisitAttractions: [
      {
        title: "Empire State Building",
        description: "The iconic 102-story Art Deco skyscraper in Midtown Manhattan.",
        cost: "$44",
        averageVisitDuration: "2h",
        bestTimeOfDay: "sunset",
        coordinates: { lat: 40.7484, lng: -73.9857 },
        openingHours: "09:00 AM - 12:00 AM",
        categories: ["landmark", "photography"],
        popularity: 98,
        accessibility: ["wheelchair_accessible"],
        weatherDependency: "high",
        photographyScore: 10,
        googleRating: 4.8,
        googleReviewsCount: 154000,
        reviews: createMockReviews("Empire State Building"),
        images: createMockImages("Empire State Building"),
        busyHours: createMockBusyHours(),
        bookingUrl: "https://www.esbnyc.com"
      },
      {
        title: "Central Park",
        description: "An urban oasis of green spaces, lakes, and paths in the middle of Manhattan.",
        cost: "Free",
        averageVisitDuration: "3h",
        bestTimeOfDay: "morning",
        coordinates: { lat: 40.7851, lng: -73.9683 },
        openingHours: "06:00 AM - 01:00 AM",
        categories: ["nature", "photography"],
        popularity: 99,
        accessibility: ["wheelchair_accessible"],
        weatherDependency: "high",
        photographyScore: 9,
        googleRating: 4.8,
        googleReviewsCount: 250000,
        reviews: createMockReviews("Central Park"),
        images: createMockImages("Central Park"),
        busyHours: createMockBusyHours()
      }
    ],
    hiddenGems: [
      {
        title: "High Line Park",
        description: "A public park built on a historic freight rail line elevated above Manhattan's West Side.",
        cost: "Free",
        averageVisitDuration: "1.5h",
        bestTimeOfDay: "afternoon",
        coordinates: { lat: 40.7480, lng: -74.0048 },
        openingHours: "07:00 AM - 10:00 PM",
        categories: ["nature", "photography"],
        popularity: 75,
        accessibility: ["wheelchair_accessible"],
        weatherDependency: "high",
        photographyScore: 8,
        isHiddenGem: true,
        googleRating: 4.7,
        googleReviewsCount: 68000,
        reviews: createMockReviews("High Line Park"),
        images: createMockImages("High Line"),
        busyHours: createMockBusyHours()
      }
    ],
    dining: {
      streetFood: [{ name: "Joe's Pizza", cuisine: "New York Pizza slice", averageCost: "$4", description: "Famous Greenwich Village pizza." }],
      fineDining: [{ name: "Le Bernardin", cuisine: "French Seafood", averageCost: "$150", description: "Elite fine dining." }],
      cafes: [{ name: "Abraço", cuisine: "Espresso", averageCost: "$5", description: "Cozy coffee shop." }]
    },
    nightlife: ["Broadway Shows", "East Village Speakeasies"],
    adventureActivities: [],
    museums: ["Metropolitan Museum of Art", "MoMA"],
    parks: ["Central Park"],
    temples: ["St. Patrick's Cathedral"],
    historicalSites: ["Statue of Liberty"],
    shoppingAreas: ["Fifth Avenue"],
    markets: ["Chelsea Market"],
    soloExperiences: [],
    coupleExperiences: [],
    familyAttractions: [],
    luxuryExperiences: [],
    budgetExperiences: [],
    localFestivals: ["Macy's Parade", "New Year's Eve Times Square"],
    travelTips: { touristScams: ["Fake CD sellers in Times Square"], packingTips: ["Warm clothes for winter, layers for fall"], generalTips: ["Buy MetroCard in advance"] },
    popularityScore: 99,
    userRating: 4.8,
    nearbyRecommendations: {}
  },
  london: {
    destination: "London",
    country: "United Kingdom",
    region: "Greater London",
    coordinates: { lat: 51.5074, lng: -0.1278 },
    language: "English",
    currency: "GBP",
    timezone: "GMT",
    bestSeason: "May to September",
    safetyScore: 92,
    crowdLevels: "high",
    weatherSummary: "Temperate maritime climate. Frequent showers, mild summers.",
    visaNotes: "Passport check at border.",
    emergencyContacts: { police: "999", medical: "999", fire: "999" },
    transportation: ["London Underground (Tube)", "Red Double Decker Buses", "Black Cabs"],
    averageCosts: { accommodation: "$160/night", food: "$45/day", transit: "$12/day", sightseeing: "$35/day" },
    mustVisitAttractions: [
      {
        title: "Tower of London",
        description: "The historic fortress and castle housing the Crown Jewels on the River Thames.",
        cost: "$40",
        averageVisitDuration: "3h",
        bestTimeOfDay: "morning",
        coordinates: { lat: 51.5081, lng: -0.0759 },
        openingHours: "09:00 AM - 05:30 PM",
        categories: ["landmark", "culture"],
        popularity: 97,
        accessibility: ["assisted_ramps"],
        weatherDependency: "low",
        photographyScore: 9,
        googleRating: 4.7,
        googleReviewsCount: 92000,
        reviews: createMockReviews("Tower of London"),
        images: createMockImages("Tower of London"),
        busyHours: createMockBusyHours(),
        bookingUrl: "https://www.hrp.org.uk/tower-of-london"
      },
      {
        title: "British Museum",
        description: "A world-renowned museum dedicated to human history, art, and culture.",
        cost: "Free",
        averageVisitDuration: "3h",
        bestTimeOfDay: "afternoon",
        coordinates: { lat: 51.5194, lng: -0.1270 },
        openingHours: "10:00 AM - 05:00 PM",
        categories: ["museum", "culture"],
        popularity: 98,
        accessibility: ["wheelchair_accessible"],
        weatherDependency: "low",
        photographyScore: 8,
        googleRating: 4.7,
        googleReviewsCount: 135000,
        reviews: createMockReviews("British Museum"),
        images: createMockImages("British Museum"),
        busyHours: createMockBusyHours()
      }
    ],
    hiddenGems: [
      {
        title: "Sky Garden",
        description: "An indoor botanical garden and observation deck offering panoramic views of London.",
        cost: "Free",
        averageVisitDuration: "1.5h",
        bestTimeOfDay: "sunset",
        coordinates: { lat: 51.5113, lng: -0.0837 },
        openingHours: "10:00 AM - 06:00 PM",
        categories: ["nature", "photography"],
        popularity: 70,
        accessibility: ["wheelchair_accessible"],
        weatherDependency: "low",
        photographyScore: 9,
        isHiddenGem: true,
        googleRating: 4.7,
        googleReviewsCount: 42000,
        reviews: createMockReviews("Sky Garden"),
        images: createMockImages("Sky Garden"),
        busyHours: createMockBusyHours(),
        bookingUrl: "https://skygarden.london"
      }
    ],
    dining: {
      streetFood: [{ name: "Borough Market Stalls", cuisine: "British Street Eats", averageCost: "$12", description: "Artisanal food market." }],
      fineDining: [{ name: "The Ledbury", cuisine: "Modern British", averageCost: "$140", description: "Two Michelin-starred dishes." }],
      cafes: [{ name: "Monmouth Coffee", cuisine: "Specialty Drip", averageCost: "$6", description: "Bustling roast shop." }]
    },
    nightlife: ["Soho Pubs", "West End Musicals"],
    adventureActivities: [],
    museums: ["British Museum", "Tate Modern"],
    parks: ["Hyde Park"],
    temples: ["Westminster Abbey"],
    historicalSites: ["Big Ben"],
    shoppingAreas: ["Oxford Street"],
    markets: ["Borough Market"],
    soloExperiences: [],
    coupleExperiences: [],
    familyAttractions: [],
    luxuryExperiences: [],
    budgetExperiences: [],
    localFestivals: ["Notting Hill Carnival"],
    travelTips: { touristScams: ["Illegal street shell games"], packingTips: ["Always carry an umbrella"], generalTips: ["Tap credit cards at Tube gates"] },
    popularityScore: 98,
    userRating: 4.8,
    nearbyRecommendations: {}
  },
  dubai: {
    destination: "Dubai",
    country: "United Arab Emirates",
    region: "Middle East",
    coordinates: { lat: 25.2048, lng: 55.2708 },
    language: "Arabic, English",
    currency: "AED",
    timezone: "GMT+4",
    bestSeason: "November to March",
    safetyScore: 96,
    crowdLevels: "high",
    weatherSummary: "Desert climate. Warm, sunny winters, blistering hot summers.",
    visaNotes: "Visa on arrival for many nationalities.",
    emergencyContacts: { police: "999", medical: "998", fire: "997" },
    transportation: ["Dubai Metro", "Careem/Taxi", "Water Taxis (Abra)"],
    averageCosts: { accommodation: "$180/night", food: "$50/day", transit: "$15/day", sightseeing: "$50/day" },
    mustVisitAttractions: [
      {
        title: "Burj Khalifa",
        description: "The tallest building in the world, dominating the Dubai skyline.",
        cost: "$48",
        averageVisitDuration: "2h",
        bestTimeOfDay: "sunset",
        coordinates: { lat: 25.1972, lng: 55.2744 },
        openingHours: "08:30 AM - 11:00 PM",
        categories: ["landmark", "photography"],
        popularity: 99,
        accessibility: ["wheelchair_accessible"],
        weatherDependency: "low",
        photographyScore: 10,
        googleRating: 4.8,
        googleReviewsCount: 220000,
        reviews: createMockReviews("Burj Khalifa"),
        images: createMockImages("Burj Khalifa"),
        busyHours: createMockBusyHours(),
        bookingUrl: "https://www.burjkhalifa.ae"
      },
      {
        title: "Dubai Mall",
        description: "A giant luxury retail mall hosting an aquarium and the famous fountains.",
        cost: "Free",
        averageVisitDuration: "4h",
        bestTimeOfDay: "afternoon",
        coordinates: { lat: 25.1985, lng: 55.2796 },
        openingHours: "10:00 AM - 12:00 AM",
        categories: ["shopping", "family"],
        popularity: 98,
        accessibility: ["wheelchair_accessible"],
        weatherDependency: "low",
        photographyScore: 8,
        googleRating: 4.7,
        googleReviewsCount: 310000,
        reviews: createMockReviews("Dubai Mall"),
        images: createMockImages("Dubai Mall"),
        busyHours: createMockBusyHours()
      }
    ],
    hiddenGems: [
      {
        title: "Al Bastakiya",
        description: "The historical quarter of Dubai, with narrow alleys, wind towers, and museums.",
        cost: "Free",
        averageVisitDuration: "2h",
        bestTimeOfDay: "morning",
        coordinates: { lat: 25.2635, lng: 55.3003 },
        openingHours: "09:00 AM - 06:00 PM",
        categories: ["culture", "photography"],
        popularity: 72,
        accessibility: [],
        weatherDependency: "high",
        photographyScore: 8,
        isHiddenGem: true,
        googleRating: 4.6,
        googleReviewsCount: 15000,
        reviews: createMockReviews("Al Bastakiya"),
        images: createMockImages("Al Bastakiya"),
        busyHours: createMockBusyHours()
      }
    ],
    dining: {
      streetFood: [{ name: "Al Mallah", cuisine: "Lebanese Shawarma", averageCost: "$10", description: "Juicy shawarmas and falafel." }],
      fineDining: [{ name: "Ossiano (Atlantis)", cuisine: "Luxury Seafood", averageCost: "$190", description: "Underwater restaurant." }],
      cafes: [{ name: "Arabian Tea House", cuisine: "Traditional Tea & Dates", averageCost: "$15", description: "Cozy courtyard cafe." }]
    },
    nightlife: ["Marina rooftop bars"],
    adventureActivities: ["Desert Dune Bashing", "Skydive Dubai"],
    museums: ["Museum of the Future"],
    parks: ["Zabeel Park"],
    temples: ["Jumeirah Mosque"],
    historicalSites: ["Al Fahidi Fort"],
    shoppingAreas: ["Gold Souk"],
    markets: ["Spice Souk"],
    soloExperiences: [],
    coupleExperiences: [],
    familyAttractions: [],
    luxuryExperiences: [],
    budgetExperiences: [],
    localFestivals: ["Dubai Shopping Festival"],
    travelTips: { touristScams: ["Fake brand vendors near Gold Souk"], packingTips: ["Modest clothing for shopping malls"], generalTips: ["Purchase Metro Silver Card"] },
    popularityScore: 97,
    userRating: 4.8,
    nearbyRecommendations: {}
  },
  singapore: {
    destination: "Singapore",
    country: "Singapore",
    region: "Southeast Asia",
    coordinates: { lat: 1.3521, lng: 103.8198 },
    language: "English, Mandarin, Malay, Tamil",
    currency: "SGD",
    timezone: "GMT+8",
    bestSeason: "December to June",
    safetyScore: 98,
    crowdLevels: "high",
    weatherSummary: "Tropical rain forest climate. Consistently warm, humid, and rainy year-round.",
    visaNotes: "SG Arrival Card required before landing.",
    emergencyContacts: { police: "999", medical: "995", fire: "995" },
    transportation: ["MRT Train Network", "SBS/SMRT Buses", "Grab rideshare"],
    averageCosts: { accommodation: "$170/night", food: "$30/day", transit: "$10/day", sightseeing: "$35/day" },
    mustVisitAttractions: [
      {
        title: "Gardens by the Bay",
        description: "The futuristic botanical garden featuring Giant Supertree structures and glass conservatories.",
        cost: "$24",
        averageVisitDuration: "3h",
        bestTimeOfDay: "sunset",
        coordinates: { lat: 1.2816, lng: 103.8636 },
        openingHours: "05:00 AM - 02:00 AM",
        categories: ["nature", "photography"],
        popularity: 99,
        accessibility: ["wheelchair_accessible"],
        weatherDependency: "low",
        photographyScore: 10,
        googleRating: 4.8,
        googleReviewsCount: 198000,
        reviews: createMockReviews("Gardens by the Bay"),
        images: createMockImages("Gardens by the Bay"),
        busyHours: createMockBusyHours(),
        bookingUrl: "https://www.gardensbythebay.com.sg"
      },
      {
        title: "Marina Bay Sands SkyPark",
        description: "The iconic rooftop observation deck offering panoramic views of Singapore Bay.",
        cost: "$20",
        averageVisitDuration: "1.5h",
        bestTimeOfDay: "sunset",
        coordinates: { lat: 1.2847, lng: 103.8610 },
        openingHours: "11:00 AM - 09:00 PM",
        categories: ["landmark", "photography"],
        popularity: 97,
        accessibility: ["wheelchair_accessible"],
        weatherDependency: "high",
        photographyScore: 9,
        googleRating: 4.7,
        googleReviewsCount: 78000,
        reviews: createMockReviews("Marina Bay Sands"),
        images: createMockImages("Marina Bay Sands"),
        busyHours: createMockBusyHours(),
        bookingUrl: "https://www.marinabaysands.com"
      }
    ],
    hiddenGems: [
      {
        title: "Kampong Glam",
        description: "Singapore's historic Muslim-Malay quarter, with boutique shopping, cafes, and mosques.",
        cost: "Free",
        averageVisitDuration: "2h",
        bestTimeOfDay: "afternoon",
        coordinates: { lat: 1.3024, lng: 103.8596 },
        openingHours: "24/7",
        categories: ["culture", "shopping"],
        popularity: 76,
        accessibility: [],
        weatherDependency: "low",
        photographyScore: 8,
        isHiddenGem: true,
        googleRating: 4.6,
        googleReviewsCount: 22000,
        reviews: createMockReviews("Kampong Glam"),
        images: createMockImages("Kampong Glam"),
        busyHours: createMockBusyHours()
      }
    ],
    dining: {
      streetFood: [{ name: "Maxwell Hawker Centre", cuisine: "Chicken Rice & local food", averageCost: "$7", description: "Famous Tian Tian Chicken Rice." }],
      fineDining: [{ name: "Odette", cuisine: "French Fine Cuisine", averageCost: "$180", description: "Three Michelin-starred restaurant." }],
      cafes: [{ name: "Chye Seng Huat Hardware", cuisine: "Specialty Cold Brew", averageCost: "$8", description: "Industrial hardware theme cafe." }]
    },
    nightlife: ["Clarke Quay bars", "Sentosa Beach clubs"],
    adventureActivities: ["Night Safari tour"],
    museums: ["National Gallery Singapore", "ArtScience Museum"],
    parks: ["Singapore Botanic Gardens"],
    temples: ["Buddha Tooth Relic Temple"],
    historicalSites: ["Fort Canning Park"],
    shoppingAreas: ["Orchard Road"],
    markets: ["Chinatown Complex Hawker Center"],
    soloExperiences: [],
    coupleExperiences: [],
    familyAttractions: [],
    luxuryExperiences: [],
    budgetExperiences: [],
    localFestivals: ["Singapore Food Festival", "National Day Parade"],
    travelTips: { touristScams: ["Overpriced seafood in tourist areas"], packingTips: ["Light summer clothes, pocket umbrella"], generalTips: ["Littering is strictly fined"] },
    popularityScore: 98,
    userRating: 4.8,
    nearbyRecommendations: {}
  }
};

// Merge original destinations to ensure complete mock database
const originalAgra = {
  destination: "Agra",
  country: "India",
  region: "Uttar Pradesh",
  coordinates: { lat: 27.1767, lng: 78.0081 },
  language: "Hindi, English",
  currency: "INR",
  timezone: "GMT+5:30",
  bestSeason: "October to March",
  safetyScore: 82,
  crowdLevels: "high",
  weatherSummary: "Mild winters, hot summers.",
  visaNotes: "e-Visa available.",
  emergencyContacts: { police: "112", medical: "102", fire: "101" },
  transportation: ["Auto rickshaws", "Ola Cabs"],
  averageCosts: { accommodation: "$40/night", food: "$12/day", transit: "$6/day", sightseeing: "$25/day" },
  mustVisitAttractions: [
    {
      title: "Taj Mahal",
      description: "The white marble mausoleum built by Shah Jahan.",
      cost: "$15",
      averageVisitDuration: "3h",
      bestTimeOfDay: "sunrise",
      coordinates: { lat: 27.1751, lng: 78.0421 },
      openingHours: "06:00 AM - 07:00 PM (Closed Friday)",
      categories: ["landmark", "culture"],
      popularity: 99,
      accessibility: ["wheelchair_accessible"],
      weatherDependency: "high",
      photographyScore: 10,
      googleRating: 4.9,
      googleReviewsCount: 385000,
      reviews: createMockReviews("Taj Mahal"),
      images: createMockImages("Taj Mahal"),
      busyHours: createMockBusyHours()
    }
  ],
  hiddenGems: [],
  dining: { streetFood: [], fineDining: [], cafes: [] },
  nightlife: [],
  adventureActivities: [],
  museums: [],
  parks: [],
  temples: [],
  historicalSites: [],
  shoppingAreas: [],
  markets: [],
  soloExperiences: [],
  coupleExperiences: [],
  familyAttractions: [],
  luxuryExperiences: [],
  budgetExperiences: [],
  localFestivals: [],
  travelTips: { touristScams: [], packingTips: [], generalTips: [] },
  popularityScore: 98,
  userRating: 4.9,
  nearbyRecommendations: {}
};

export class MockKnowledgeProvider implements DestinationKnowledgeProvider {
  name = "MockKnowledgeProvider";

  async fetchDestinationKnowledge(destination: string): Promise<DestinationKnowledge | null> {
    const key = destination.toLowerCase().trim().replace(/[^a-z0-9]/g, "");
    
    // Add Agra fallback
    if (key.includes("agra")) return originalAgra as any;

    const matchedKey = Object.keys(MOCK_DESTINATIONS).find(k => k === key || key.includes(k) || k.includes(key));
    if (matchedKey) {
      return MOCK_DESTINATIONS[matchedKey];
    }
    
    // Default fallback mock to prevent blank screens
    return MOCK_DESTINATIONS["rome"];
  }
}
